name: Docker Image CI
on:
  push:
    branches: [ "public" ]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:

    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Configure Google Cloud Authentication'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
        workload_identity_provider: 'projects/623115008327/locations/global/workloadIdentityPools/public-facing/providers/github-actions'
        service_account: 'thomps9012@finance-api-361311.iam.gserviceaccount.com'

    - id: 'gcloud'
      name: 'gCloud Service List'
      run: |-
        gcloud auth login --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list --project='finance-api'
    
    - name: 'Configures Gcloud Docker'
      run: gcloud auth configure-docker
    
    - name: 'Lists Images in Gcloud'
      run: gcloud container images list-tags gcr.io/finance-api/appengine/default.20220902t121147

    - name: 'Build the Docker Image'
      run: docker build -t public-finance-api .

    - name: 'Tags the Docker Image for the Google Container Registry'
      run: docker tag public-finance-api gcr.io/finance-api/appengine/default.20220902t121147

    - name: 'Pushes the Docker Image to the Google Container Registry'
      run: docker push gcr.io/finance-api/appengine/default.20220902t121147