name: Go
env:
  ATLAS_URI: ${{ secrets.ATLAS_URI }}
  DB_NAME: ${{ secrets.DB_NAME }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  testENV:
    runs-on: ubuntu-latest
    steps:
      - name: "print env variables"
        run: echo "Atlas uri $ATLAS_URI, Database $DB_NAME, jwt key $JWT_KEY"
      
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          go-version: 1.18
    - name: Build
      run: go build -v ./...
      
    - name: Run
      run: go run main.go
      env:
        ATLAS_URI: ${{ secrets.ATLAS_URI }}
        DB_NAME: ${{ secrets.DB_NAME }}
        JWT_KEY: ${{ secrets.JWT_KEY }}
